version: '3'

interval: 500ms

tasks:
  default:
    desc: transpile Sass to CSS
    sources:
      - style/**/*.scss
    generates:
      - static/css/**/*.css
      - static/css/**/*.css.map
    cmds:
      - for: "sources"
        cmd: ./bin/compile-scss {{.ITEM}}
