#!/usr/bin/fish

# Functions

function log
	printf '%s[INFO] %s%s\n' (set_color brcyan) $argv (set_color normal)
end

function die
	printf '%s[FATAL] %s%s\n' (set_color brred) $argv (set_color normal)
	exit 1
end

function usage
	echo "Usage: $(status -f) <gallery_name> <imgur_slug>\n"
	exit 1
end

# Arguments

set name $argv[1]
set slug $argv[2]

if test -z "$name"
	usage
end

if test -z "$slug"
	usage
end

# Constants

set imgur_base_url "https://imgur.com/gallery"
set gallery_config_template "https://raw.githubusercontent.com/jaunty/snippets/refs/heads/trunk/gallery-dl.json"
set working_dir "images"
set supported_exts .jpg .json

# The following are the external programs this script requires to function.
# * jq is required for JSON manipulation.
# * curl is required for downloading snippets.
# * ImageMagick is required for converting image files.
# * gallery-dl is required for retrieving the images from Imgur.
set dependencies jq curl magick gallery-dl

for dep in $dependencies
	if ! command -q $dep
		die "Dependency \"$dep\" was not found on your system. Please install it and try again"
	end
end

if ! test -e $working_dir
	log "Creating base directory ($working_dir)"
	command mkdir $working_dir
end

set gldl_config "$working_dir/gallery-dl.json"

if ! test -e $gldl_config
	log "Downloading gallery-dl configuration file from GitHub"
	command curl -s -L -o $gldl_config $gallery_config_template
end

set gallery_dir "$working_dir/$name"

if test -e $gallery_dir
	log "Recreating gallery directory ($gallery_dir)"
	command rm -rf $gallery_dir
	command mkdir $gallery_dir
else
	log "Creating gallery directory ($gallery_dir)"
	command mkdir $gallery_dir
end

log "Downloading images from Imgur"
command gallery-dl -q -D $gallery_dir -c $gldl_config (printf "%s/%s" $imgur_base_url $slug)
log "$(count (ls $gallery_dir/*.{png,jpg})) images downloaded successfully"

set json "[]"
set json_path $gallery_dir/$name.json

for image in $gallery_dir/*.{png,jpg}
	set image_name (path basename $image)
	set image_ext (path extension $image_name)
	set image_id (path change-extension '' $image_name)

	log "$image_id: processing image"

	set new_id (command cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)

	set static_path "/static/image/screenshot/$name/$new_id.jpg"
	set caption ""

	set caption_file $gallery_dir/$image_id
	if test -e $caption_file
		log "$image_id: found caption for image"
		set caption (command cat $caption_file)
		command rm $caption_file
	end

	set json (command echo $json | jq --arg url "$static_path" --arg caption "$caption" '. += [{"url": $url, "caption": $caption}]')

	if test "$image_ext" != ".jpg"
		log "$image_id: converting image from PNG to JPEG"
		command magick $image $gallery_dir/$new_id.jpg
	else
		command mv $image $gallery_dir/$new_id.jpg
	end

	log "$image_id: image renamed to $new_id.jpg"
end

log "Writing JSON to file"
echo $json > $json_path

log "Cleaning up"
for file in $gallery_dir/*
	set file_name (path basename $file)
	set file_ext (path extension $file_name)
	set file_id (path change-extension '' $file_name)

	if ! contains $file_ext $supported_exts
		command rm $file
		set caption_file $gallery_dir/$file_id
		if test -e $caption_file
			command rm $caption_file
		end
	end
end
